import "../globals.css";

import Head from "next/head";
import { Roboto_Condensed } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./components/Navbar/Navbar";
import NavbarMbl from "./components/Navbar/NavbarMbl";
import Footer from "./components/Footer/Footer";
import Sidebar from "./components/Sidebar/Sidebar";

export const metadata = {
  title:
    "Department of Computer Science and Engineering - Sunamgonj Science and Technology University",
  description: "Generated by create next app",
};

const PTSans = Roboto_Condensed({
  weight: ["400", "700"],
  subsets: ["cyrillic-ext", "latin"],
});

const myFont = localFont({
  src: "../../public/fonts/HindSiliguri-Regular.ttf",
});

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <html lang="en">
        <body className={myFont.className}>
          {/* Main layout */}
          <div className="sm:relative">
            {/* Desktop navigation */}
            <div className="sm:block sm:fixed sm:top-0 z-[999999999999] sm:w-full hidden">
              <Navbar />
            </div>
            {/* Mobile navigation */}
            <div className="sm:hidden fixed top-0 z-[999999999999]">
              <NavbarMbl />
            </div>

            {/* Main content area */}
            <div className="sm:grid grid-cols-12 min-h-screen hidden max-h-full">
              <div className="sm:col-span-2 bg-white shadow-[rgba(0,0,15,0.1)_1px_0px_0px_0px]">
                <div className="fixed top-7 sm:top-48 w-fit">
                  <Sidebar />
                </div>
              </div>
              <div className="sm:col-span-10 mt-16 sm:mt-36 hidden sm:block ">
                {children}
              </div>
            </div>
            <Footer />
          </div>

          {/* Mobile layout */}
          <div className="sm:hidden">
            <div className="fixed top-7 sm:top-48 w-fit z-[999999999999]">
              <Sidebar />
            </div>

            <div className="max-h-full">{children}</div>
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
