import "../globals.css";

import Head from "next/head";
import { Roboto_Condensed } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Career - Sunamgonj Science and Technology University",
  description: "Generated by create next app",
};

const PTSans = Roboto_Condensed({
  weight: ["400", "700"],
  subsets: ["cyrillic-ext", "latin"],
});

const myFont = localFont({
  src: "../../public/fonts/HindSiliguri-Regular.ttf",
});

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <html lang="en">
        <body className={myFont.className}>
          {/* Main layout */}
          <div className="sm:relative">
            {/* Desktop navigation */}
            <div className="sm:block sm:fixed sm:top-0 sm:w-full ">
              <Navbar />
            </div>
            <div className="min-h-screen  bg-cover bg-center pt-48">
              {children}
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
