import "../globals.css";
import NavbarResponsive from "@/components/layouts/navbar/NavbarResponsive";
import Footer from "@/components/layouts/footer/Footer";
import Head from "next/head";
import { Roboto_Condensed } from "next/font/google";
import localFont from "next/font/local";

export const metadata = {
  title: "Sunamgonj Science and Technology University",
  description: "Generated by create next app",
};

const PTSans = Roboto_Condensed({
  weight: ["400", "700"],
  subsets: ["cyrillic-ext", "latin"],
});

const myFont = localFont({
  src: "../../public/fonts/HindSiliguri-Regular.ttf",
});

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <html lang="en">
        <body className={myFont.className}>
          <NavbarResponsive />
          <div>{children}</div>
          <Footer />
        </body>
      </html>
    </>
  );
}
